name: Deno

on:
  - push

jobs:
  format:
    runs-on: ubuntu-20.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.41.1"

      - name: Format
        run: deno task format:check

  check:
    runs-on: ubuntu-20.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.41.1"

      - name: Build Artifacts
        run: |
          deno task artifacts:build

          if ! git diff --exit-code || ! git diff --staged --exit-code; then
            echo "Error: Genreated artifacts are not up to date."
            exit 1
          fi

      - name: Check
        run: deno task check:dirty

      - name: Lint
        run: deno task lint:dirty

